language: python
python:
  - "3.6"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libxml2-dev

install: 
  - pip install -r webapp/requirements.txt

script: 
  - cd webapp
  - python -m unittest discover

deploy:
  provider: heroku
  api_key:
    secure: c4541dd5-7e68-4a4d-b081-3446d7809673
