language: python
python:
- '3.6'
env:
  PROJECT_PATH=webapp
before_install:
- sudo apt-get update
- sudo apt-get install -y libxml2-dev
install:
- pip install -r webapp/requirements.txt
script:
- cd webapp
- python -m unittest discover
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: 7da7b609-cf72-4e49-b12d-e13ed50189b7
  app: indel-app
