# Configuration file for classification_neural_network.py
# The neural network will load the config files from ~/machine-learning/.nn_config.yml unless
# specified otherwise using --config <path/to/config/file> 

# Command-line values override environment variables which override config file values which
# override defaults

# Number of cpus the program should use
# Sometimes the program freezes and shows '1/100 Epochs' four times when using more than 1 cp 
# To avoid this source setup.sh before running the neural net, change cpu to 1 or comment out code relating to cross validation 
cpu: -1

# File to be analysed (Default: Neural_network_Example_summary.csv)
# Make sure the data preprocessing script has been run on the file beforehand
sample: /home/ubu/machine-learning-data/merged_data/classification_52bp_miseq26_merged_data.csv
#sample: /home/ubu/data/machine-learning-data/encoded_input.csv

# File containing encoded output. Must be supplied when using batch flag. Input file goes with --sample
#output: /home/ubu/data/machine-learning-data/encoded_output.csv

# Batch mode
# Use batch mode when data is too big to fit into memory, point --sample to encoded input file and --output to encoded output file
# Can encode data using encode_data.py
# DO NOT USE --predict when using batch mode. Save the trained model then can run prediction on the saved model. 
#batch: 1 

# Path to save model (Default: ~/machine-learning/snapshots/classification/{date}_trained_model.h5)
#save: /home/ubu/data/machine-learning-data/machine-learning/snapshots/classification/full_classification_trained_model.h5

# Prediction on a single observation
# Must be in the same format and order as a csv produced by data_preprocessing.pl minus the aligned sequence
#predict: TG,AG,AA,AA,CC,AA,AC,AG,GG,TG,TG,GC,AG,AA,GC,AG,CA,GG,AA,AG,AC,AA,AA,GA,GG,GA

# Load an existing model 
# Default: /home/ubuntu/machine-learning/snapshots/03-05-18_best_model.h5
#load: /home/ubuntu/machine-learning/snapshots/classification/13-06-18_trained_model.h5

# Path of dir to save tensorboard of new model 
# When the model finishes program will automatically open tensorboard in the browser
#tensorboard: /home/ubuntu/machine-learning/tensorboard/classification/13-06-18_classification_tensorboard
